Update voltha

diff --git a/voltha b/voltha
--- a/voltha
+++ b/voltha
@@ -114,12 +114,12 @@ fi
 # note: instances will be numbered from 0 to 9
 if [ "$1" == "up" ]; then
 	if [ "$NUM_OF_BBSIM" -lt 1 ]; then 
-			echo -e "   ${RED}Setting of BBSIM instances to minimum instances of 1!${NORMAL}"
-			NUM_OF_BBSIM=1
+			>&2 echo -e "${RED}${BOLD}${ERROR}ERROR:${NORMAL}${RED} Invalid setting of BBSIM instances. NUM_OF_BBSIM is less than 1${NORMAL}"
+			exit 1
 	fi
-	if [ "$NUM_OF_BBSIM" -gt $(($MAX_NUM_OF_BBSIM)) ]; then 
-			echo -e "   ${RED}Setting of BBSIM instances to max supported instances of $MAX_NUM_OF_BBSIM!${NORMAL}"
-			NUM_OF_BBSIM=$MAX_NUM_OF_BBSIM
+	if [ "$NUM_OF_BBSIM" -gt $MAX_NUM_OF_BBSIM ]; then 
+			>&2 echo -e "${RED}${BOLD}${ERROR}ERROR:${NORMAL}${RED} Invalid setting of BBSIM instances. NUM_OF_BBSIM is greater than $MAX_NUM_OF_BBSIM${NORMAL}"
+			exit 1
 	fi
 fi
 # Verify TYPE setting
@@ -396,32 +396,15 @@ push_onos_config() {
     local RESOURCE=$3
     local DATA=$4
 
-    # Thanks to the latest version of ONOS using the return code 207 this gets a
-    # whole lot nastier. Can't thank them enough for doing this. So in order to
-    # capture the command and the output in the log file as well as capture the
-    # status code to verify it is 200 and not 207 mutltiple files and a bit of
-    # hackery must be used. Thanks again ONOS.
-    local CMD_ECHO=$(mktemp -u)
-    local CMD_OUTPUT=$(mktemp -u)
-    local SC_OUTPUT=$(mktemp -u)
-
     bspin - "$MSG $GEAR"
     while true; do
         if [ $TYPE == "file" ]; then
-          (set -x; curl --fail -sSL --user karaf:karaf -w "%{http_code}" -o $CMD_OUTPUT -X POST -H Content-Type:application/json http://127.0.0.1:$ONOS_API_PORT/onos/v1/$RESOURCE --data @$DATA >$SC_OUTPUT 2>/dev/null) >>$CMD_ECHO 2>&1
+          (set -x; curl --fail -sSL --user karaf:karaf -X POST -H Content-Type:application/json http://127.0.0.1:$ONOS_API_PORT/onos/v1/$RESOURCE --data @$DATA >>$LOG 2>&1) >>$LOG 2>&1
         fi
         if [ $TYPE == "json" ]; then
-          (set -x; curl --fail -sSL --user karaf:karaf -w "%{http_code}" -o $CMD_OUTPUT -X POST -H Content-Type:application/json http://127.0.0.1:$ONOS_API_PORT/onos/v1/$RESOURCE --data $DATA >$SC_OUTPUT 2>/dev/null) >>$CMD_ECHO 2>&1
+          (set -x; curl --fail -sSL --user karaf:karaf -X POST -H Content-Type:application/json http://127.0.0.1:$ONOS_API_PORT/onos/v1/$RESOURCE --data $DATA >>$LOG 2>&1) >>$LOG 2>&1
         fi
-        RESULT=$?
-        # Dump everything to the log
-        cat $CMD_ECHO >> $LOG
-        cat $CMD_OUTPUT >> $LOG
-        SC=$(cat $SC_OUTPUT)
-
-        # clean up temp files
-        rm -f $CMD_ECHO $CMD_OUTPUT $SC_OUTPUT
-        if [ $RESULT -eq 0 -a "$SC" == "200" ]; then
+        if [ $? -eq 0 ]; then
             break
         fi
         sleep 1
@@ -619,7 +602,10 @@ if [ "$1" == "down" ]; then
         fi
     else
         EXISTS=$(helm list -q)
-        EXPECT="etcd-operator onos open-olt open-onu sim voltha bbsim bbsim1 bbsim2 bbsim3 bbsim4 bbsim5 bbsim6 bbsim7 bbsim8 bbsim9 radius"
+        EXPECT="etcd-operator onos open-olt open-onu sim voltha bbsim radius"
+		for instance in $(seq 1 $(($MAX_NUM_OF_BBSIM-1))); do
+			EXPECT="$EXPECT bbsim$instance"
+		done
         bspin "Remove Helm Deployments"
         for i in $EXISTS; do
             if [ $(echo $EXPECT | grep -c $i) -eq 1 ]; then
@@ -1249,8 +1235,7 @@ if [ $WITH_BBSIM == "yes" ]; then
     STIME=$(date +%s)
     echo -e "Verify BBSIM $PLUG"
     bspin - "Verify BBSIM Installed"
-	for instance in $(seq 0 $(($NUM_OF_BBSIM-1)));
-	do
+	for instance in $(seq 0 $(($NUM_OF_BBSIM-1))); do
 		if [ $instance -eq 0 ]; then
 			instance_num=""
 		else
